server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product_service
              uri: http://localhost:8082
              predicates:
                - Path=/products/**
            - id: user_service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**

